Update ci-linux-aarch64.yml

diff --git a/.github/workflows/ci-linux-aarch64.yml b/.github/workflows/ci-linux-aarch64.yml
--- a/.github/workflows/ci-linux-aarch64.yml
+++ b/.github/workflows/ci-linux-aarch64.yml
@@ -86,7 +86,7 @@ jobs:
             echo "ERROR: PROTOCOL_VERSION is not 62055"; exit 1
           }
           grep -qE 'MIN_PEER_PROTO_VERSION[[:space:]]*=[[:space:]]*62052' src/version.h || {
-            echo "ERROR: MIN_PEER_PROTO_VERSION is not 62055"; exit 1
+            echo "ERROR: MIN_PEER_PROTO_VERSION is not 62052"; exit 1
           }
           echo "OK: clientversion.h BUILD=7, version.h PROTOCOL=62055"
 
